# This is a basic workflow to help you get started with Actions

name: Matrix reporting

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  matrix:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.set-repos.outputs.repos }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_repos
        with:
          route: GET /orgs/{owner}/repos
          owner: dsp-testing
        env:
          GITHUB_TOKEN: ${{ secrets.APT_TOKEN }}
      - id: set-repos
        run: |
          export REPOS=`echo '${{ steps.get_repos.outputs.data }}' | jq 'map(.full_name)'`
          echo $REPOS
          echo "::set-output name=repos::$REPOS"
      
      - run: echo ${{ steps.set-repos.outputs.repos }}
  
  build:
    strategy:
      fail-fast: false
      matrix:
        repos: [ 'dsp-testing/ghas-intro-6', 'amitgupta7/webgoat' ]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - run: echo ${{ needs.matrix.outputs.repos }}

    - uses: amitgupta7/ghas-reports-action@v3.5
      with:
        token: ${{ secrets.APT_TOKEN }}
        # optionally define repo (default is calling repo)
        repo: ${{ matrix.repos }}
        
    - name: Run a one-line script
      run: |
        REPO=${{ matrix.repos }}
        ARTIFACT="${REPO//\//_}"
        echo "::set-output name=ARTIFACT_NAME::$ARTIFACT"
      id: artifact-name
  

    - uses: actions/upload-artifact@v3.0.0
      with:
        name: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}
        path: alerts.xlsx   
           
