# This is a basic workflow to help you get started with Actions

name: Matrix reporting

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  build:
    strategy:
      fail-fast: false
      matrix:
        repos: [ 'dsp-testing/ghas-intro-6', 'amitgupta7/webgoat' ]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        # Generate issues and save results
    - uses: amitgupta7/ghas-reports-action@v3.5
      with:
        token: ${{ secrets.APT_TOKEN }}
        # optionally define repo (default is calling repo)
        repo: ${{ matrix.repos }}
        
    - name: Run a one-line script
      run: echo "::set-output name=ARTIFACT_NAME::${{ matrix.repos }}"
      id: artifact-name
  
  #run: echo "The selected color is ${{ steps.random-color-generator.outputs.SELECTED_COLOR }}"

    - uses: actions/upload-artifact@v3.0.0
      with:
        name: ${{ steps.artifact-name.outputs.ARTIFACT_NAME}}
        path: alerts.xlsx   
           
