# This is a basic workflow to help you get started with Actions

name: Matrix reporting

# Controls when the workflow will run
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-repos-for-org:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.set-repos.outputs.MATRIX }}
    steps:
      - uses: octokit/request-action@v2.x
        id: get_repos
        with:
          route: GET /orgs/{owner}/repos
          owner: dsp-testing
        env:
          GITHUB_TOKEN: ${{ secrets.APT_TOKEN }}
      - id: set-repos
        run: |
          REPOS=`echo '${{ steps.get_repos.outputs.data }}' | jq 'map(.full_name)'`
          echo '::set-output name=MATRIX::'$REPOS

  # check-matrix:
  #   runs-on: ubuntu-latest
  #   needs: get-repos-for-org
  #   steps:
  #     - name: Install json2yaml
  #       run: |
  #         sudo npm install -g json2yaml

  #     - name: Check matrix definition
  #       run: |
  #         matrix='${{ needs.get-repos-for-org.outputs.repos }}'
  #         echo $matrix
  #         echo $matrix | jq .
  #         echo $matrix | json2yaml

  build:
    needs: get-repos-for-org
    strategy:
      fail-fast: false
      matrix:
        repos: ${{fromJson(needs.get-repos-for-org.outputs.repos)}}
        #[ 'dsp-testing/ghas-intro-6', 'amitgupta7/webgoat' ]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - uses: amitgupta7/ghas-reports-action@v3.5
      with:
        token: ${{ secrets.APT_TOKEN }}
        # optionally define repo (default is calling repo)
        repo: ${{ matrix.repos }}
        
    - name: Run a one-line script
      run: |
        REPO=${{ matrix.repos }}
        ARTIFACT="${REPO//\//_}"
        echo "::set-output name=ARTIFACT_NAME::$ARTIFACT"
      id: artifact-name
  

    - uses: actions/upload-artifact@v3.0.0
      with:
        name: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}
        path: alerts.xlsx   
           
